default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: towers_game_development

test:
  <<: *default
  database: towers_game_test

production:
  <<: *default
  database: towers_game_production
  username: towers_game
  password: <%= ENV["TOWERS_GAME_DATABASE_PASSWORD"] %>
